Task : T/21/005288
open-synergy/opnsynid-l10n-indonesia-vertical-accountant pull request #4
Opened 2022-02-20 04:33 UTC by Asrulbastian

Pembuatan Modul Baru

2022-02-21 02:14 UTC, mikevhe18 requested changes

2022-02-21 02:14 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bni/data/accountant_report_stakeholder_report_type_data.xml
> +        <field name="name">BNI</field>
Bank Negara Indonesia

2022-02-21 02:14 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_cancel_reason_configurator_data.xml
> +            <field name="method_cancel_name">workflow_action_cancel</field>
method_cancel_name = action_cancel
**NOTE:** Method **workflow_action_cancel** tidak ada, jangan lupa untuk selalu coba setiap flow tombol

2022-02-21 02:14 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
Tidak perlu disearch dari type, lgsg gunakan "**result = document.type_id.confirm_grp_ids.ids**"

2022-02-21 02:14 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
Tidak perlu disearch dari type, lgsg gunakan "**result = document.type_id.cancel_grp_ids.ids**"

2022-02-21 02:14 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
Tidak perlu disearch dari type, lgsg gunakan "result = document.type_id.restart_grp_ids.ids"

2022-02-21 02:14 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
Tidak perlu disearch dari type, lgsg gunakan "result = document.type_id.restart_validation_grp_ids.ids"

2022-02-21 15:57 UTC, Asrulbastian commented on l10n_id_accountant_report_stakeholder_report_bni/data/accountant_report_stakeholder_report_type_data.xml
> +        <field name="name">BNI</field>
done

2022-02-21 15:58 UTC, Asrulbastian commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_cancel_reason_configurator_data.xml
> +            <field name="method_cancel_name">workflow_action_cancel</field>
baik mike. done

2022-02-21 15:58 UTC, Asrulbastian commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
done

2022-02-21 15:58 UTC, Asrulbastian commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
done

2022-02-21 15:58 UTC, Asrulbastian commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
done

2022-02-21 15:58 UTC, Asrulbastian commented on l10n_id_accountant_report_stakeholder_report_bni/data/base_workflow_policy_stakeholder_report_bni_data.xml
> +            </field>
done

2022-02-24 23:18 UTC, andhit-r commented
@Asrulbastian @mikevhe18 

PR dah gw merge di branch lain. PR ini gw push revisi gw untuk dipelajari. Mohon dipelajari agar kesalahan yang sama tidak terjadi ke depannya

2022-02-24 23:18 UTC, closed without merging