[l10n_id_accountant_report_stakeholder_report_bpk] 8.0.1.0.0
open-synergy/opnsynid-l10n-indonesia-vertical-accountant pull request #5
Opened 2022-02-21 10:40 UTC by azmimr67

* Task 8.0-T005297
* Pembuatan Awal
* Revisi sesuai github
* Pindah repo

2022-02-22 22:44 UTC, mikevhe18 requested changes

2022-02-22 22:44 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_sequence_configurator_data.xml
> +    <field name="sequence_computation_code">result = False
"**result = False**" dihapus

2022-02-22 22:44 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +    <field name="python_code">result = allowed_wokflow_policy.cancel_grp_ids.ids
result = document.type_id.cancel_grp_ids.ids

2022-02-22 22:44 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +    <field name="python_code">result = allowed_wokflow_policy.restart_grp_ids.ids
result = document.type_id.restart_grp_ids.ids

2022-02-22 22:44 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +            >result = allowed_wokflow_policy.restart_validation_grp_ids.ids
result = document.type_id.restart_validation_grp_ids.ids

2022-02-22 22:44 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +    <field name="python_code">result = allowed_wokflow_policy.confirm_grp_ids.ids
result = document.type_id.confirm_grp_ids.ids

2022-02-22 22:44 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bpk/README.rst
> +1.  Clone the branch 8.0 of the repository https://github.com/open-synergy/opnsynid-vertical-accountant
https://github.com/open-synergy/opnsynid-l10n-indonesia-vertical-accountant

2022-02-22 22:44 UTC, mikevhe18 commented on l10n_id_accountant_report_stakeholder_report_bpk/README.rst
> +<https://github.com/open-synergy/opnsynid-vertical-accountant/issues>`_.
https://github.com/open-synergy/opnsynid-l10n-indonesia-vertical-accountant

2022-02-22 22:46 UTC, mikevhe18 commented
**NOTE:** Tolong jangan lupa untuk dicoba dulu, terutama untuk modul policy, multiple approval, dll.

2022-03-03 09:10 UTC, azmimr67 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_sequence_configurator_data.xml
> +    <field name="sequence_computation_code">result = False
done

2022-03-03 09:12 UTC, azmimr67 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +    <field name="python_code">result = allowed_wokflow_policy.cancel_grp_ids.ids
done

2022-03-03 09:12 UTC, azmimr67 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +            >result = allowed_wokflow_policy.restart_validation_grp_ids.ids
done

2022-03-03 09:13 UTC, azmimr67 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +    <field name="python_code">result = allowed_wokflow_policy.restart_grp_ids.ids
done

2022-03-03 09:14 UTC, azmimr67 commented on l10n_id_accountant_report_stakeholder_report_bpk/data/base_workflow_policy_stakeholder_report_bpk_data.xml
> +    <field name="python_code">result = allowed_wokflow_policy.confirm_grp_ids.ids
done

2022-03-03 09:14 UTC, azmimr67 commented on l10n_id_accountant_report_stakeholder_report_bpk/README.rst
> +1.  Clone the branch 8.0 of the repository https://github.com/open-synergy/opnsynid-vertical-accountant
done

2022-03-03 09:15 UTC, azmimr67 commented on l10n_id_accountant_report_stakeholder_report_bpk/README.rst
> +<https://github.com/open-synergy/opnsynid-vertical-accountant/issues>`_.
done

2022-04-14 01:39 UTC, closed without merging